# Generated by Django 5.2 on 2025-06-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_address_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='time_of_birth',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
